### ISSUE TITLE
macOS support?

### ISSUE THREAD

**Issue by cortrano** [RevoluPowered/one-voip-godot-4#14]
Is that possible to add macOS support?

**Comment by marc-weber1** [comment]
From what I understand gdextensions will only work if you sign them with the apple $100 developer license, and modules will only work if you recompile the entire engine using this code. I've considered a module version but I have no macs I could test it on

**Comment by Cortrano** [comment]
> From what I understand gdextensions will only work if you sign them with the apple $100 developer license, and modules will only work if you recompile the entire engine using this code. I've considered a module version but I have no macs I could test it on

I'm sure that $100 license is unnecessary because it's required only for posting apps in AppStore. For example I've already built gdextension libs for tbloader and godot-steam addons absolutely for free. I will try to build this lib too

**Comment by Cortrano** [comment]
Haven't figure out how to compile it for mac on m1. I successfully compiled opus lib running `cmake -Bbuild -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"`

But i get errors like "This header is only meant to be used on x86 and x64 architecture" in thirdparty/speex/libspeexdsp/resample.c and thirdparty/speex/libspeexdsp/resample_sse when try to run `scons platform=macos arch=arm64`

And when i try to run  `scons platform=macos arch=x86_64` looks like it builds successfully

**Comment by marc-weber1** [comment]
If you look in the SConstruct file you'll see these lines I just hardcoded for x86:
```
# Speex (resampler / jitter buffer)

env.Append(CPPPATH=["thirdparty/speex/include"])
env.Append(CPPDEFINES={"USE_SSE": None, "USE_SSE2": None, "FLOATING_POINT": None, "USE_SMALLFT": None}) # "EXPORT": None ?
sources += ["thirdparty/speex/libspeexdsp/resample.c", "thirdparty/speex/libspeexdsp/jitter.c"]
```

Obviously USE_SSE and USE_SSE2 will not work on ARM; it has something else it uses for float vectors called NEON. For a temporary fix, just remove the SSE defines, but if you want to help make the code a bit faster try finding a USE_NEON header or something like that in the speex resample header (and tell me what it is pls)

**Comment by marc-weber1** [comment]
(Looks like it is USE_NEON - if that gets it to build lmk)

**Comment by Cortrano** [comment]
<img width="1050" alt="image" src="https://github.com/RevoluPowered/one-voip-godot-4/assets/61734748/774cc785-f576-4646-acea-d6d1aa6b4ca9">
I get this error on your pr :(


`In file included from src/audio_stream_voip.cpp:3:
include/audio_stream_voip.h:7:10: fatal error: 'opus.h' file not found
#include "opus.h"
         ^~~~~~~~
In file included from src/audio_stream_playback_voip.cpp:1:
In file included from include/audio_stream_playback_voip.h:7:
include/audio_stream_voip.h:7:10: fatal error: 'opus.h' file not found
#include "opus.h"
         ^~~~~~~~
In file included from src/register_types.cpp:3:
In file included from include/voip_input_capture.h:6:
include/audio_stream_voip.h:7:10: fatal error: 'opus.h' file not found
#include "opus.h"
         ^~~~~~~~
In file included from src/voip_input_capture.cpp:1:
In file included from include/voip_input_capture.h:6:
include/audio_stream_voip.h:7:10: fatal error: 'opus.h' file not found
#include "opus.h"
         ^~~~~~~~
1 error generated.
1 error generated.
1 error generated.
1 error generated.
scons: *** [src/audio_stream_playback_voip.os] Error 1
scons: *** [src/audio_stream_voip.os] Error 1
scons: *** [src/register_types.os] Error 1
scons: *** [src/voip_input_capture.os] Error 1
scons: building terminated because of errors.`

**Comment by Cortrano** [comment]
It look like you forgot add macOS here
`elif env["platform"] == "linux" or env["platform"] == "javascript" or env["platform"] == "macos":
    env.Append(CPPPATH=["thirdparty/opus/include"], LIBS=["opus"], LIBPATH="thirdparty/opus/build")
    env.Append(CXXFLAGS = ['-fpermissive'])`
    
Now it works!

**Comment by Cortrano** [comment]
I also tested buld for x86_64 and now it fails with:

`In file included from thirdparty/speex/libspeexdsp/resample.c:104:
thirdparty/speex/libspeexdsp/resample_neon.h:213:12: error: unknown register name 'q0' in asm
         : "q0");
           ^
thirdparty/speex/libspeexdsp/resample_neon.h:334:13: error: unknown register name 'q0' in asm
                  : "cc", "q0", "q1", "q2", "q3",
                          ^
2 errors generated.
clang++ -o src/voip_input_capture.os -c -fno-exceptions -std=c++17 -fpermissive -arch x86_64 -O2 -fvisibility=hidden -fPIC -DHOT_RELOAD_ENABLED -DMACOS_ENABLED -DUNIX_ENABLED -DDEBUG_ENABLED -DDEBUG_METHODS_ENABLED -DNDEBUG -DFLOATING_POINT -DUSE_SMALLFT -DUSE_NEON -Igodot-cpp/gdextension -Igodot-cpp/include -Igodot-cpp/gen/include -Ithirdparty/opus/include -Ithirdparty/speex/include -Ithirdparty -Iinclude src/voip_input_capture.cpp
scons: *** [thirdparty/speex/libspeexdsp/resample.os] Error 1
scons: building terminated because of errors.`

**Comment by marc-weber1** [comment]
put the first two thru, but that last one makes it seem like resampler_neon is getting included - not sure if building both at once is the issue?

**Comment by marc-weber1** [comment]
@Cortrano reviving this one more time - lmk if the pull request builds on mac, or if there's any fixes I can do to make it build if not

**Comment by Cortrano** [comment]
@marc-weber1 with your pull request I can build for arm, but not for x86_64 on mac.

**Comment by Cortrano** [comment]
@marc-weber1 Sorry for long wait before response. With your current pull request I can build for arm, but not for x86_64 on mac. 

On current branch, though, build for x86_64 works

**Comment by marc-weber1** [comment]
The only possible way you could be getting an error like `In file included from thirdparty/speex/libspeexdsp/resample.c:104: thirdparty/speex/libspeexdsp/resample_neon.h` is if [use neon](https://github.com/RevoluPowered/one-voip-godot-4/pull/15/files#diff-d78c5c377c03dd251edc72cdb0ae7d9986fa08361eb392187218f8c670c0bc4eR35) is true - are you absolutely sure you're compiling with `scons platform=macos arch=x86_64` ?

**Comment by cgodley** [comment]
I was able to build, run, and hear audio by running `demo_server` and 2x `demo` on mac m1 (arm64) Sonoma 14.3 without signing anything

* I had to change Godot project settings `Audio > Driver > Mix Rate` to `48000` to avoid this issue: https://github.com/godotengine/godot/issues/58180

* `USE_NEON` works when I run `scons platform=macos arch=arm64` but not plain `scons`, likely because it's building a universal binary that includes `x86_64`, which does not have neon support.

* I can only hear audio in my left ear and I get a lot of `NOT ENOUGH SAMPLES` warnings.

* For reference, here is my diff from `main` (`commit ba6f17f11a01ea3e0dff2e6582c44436c5361c02 (HEAD -> main, origin/main, origin/HEAD)`):

```diff
diff --git a/SConstruct b/SConstruct
index fc97dcd..09cb531 100644
--- a/SConstruct
+++ b/SConstruct
@@ -23,15 +23,17 @@ if env["platform"] == "windows":
 elif env["platform"] == "linux" or env["platform"] == "javascript":
     env.Append(CPPPATH=["thirdparty/opus/include"], LIBS=["opus"], LIBPATH="thirdparty/opus/build")
     env.Append(CXXFLAGS = ['-fpermissive'])
-
+elif env["platform"] == "macos":
+    env.Append(CPPPATH=["thirdparty/opus/include"], LIBS=["opus"], LIBPATH="thirdparty/opus/build")
 
 # Speex (resampler / jitter buffer)
-
 env.Append(CPPPATH=["thirdparty/speex/include"])
-env.Append(CPPDEFINES={"USE_SSE": None, "USE_SSE2": None, "FLOATING_POINT": None, "USE_SMALLFT": None}) # "EXPORT": None ?
+if env["platform"] == "macos":
+    env.Append(CPPDEFINES=['FLOATING_POINT', 'USE_NEON'])
+else:
+    env.Append(CPPDEFINES={"USE_SSE": None, "USE_SSE2": None, "FLOATING_POINT": None, "USE_SMALLFT": None}) # "EXPORT": None ?        
 sources += ["thirdparty/speex/libspeexdsp/resample.c", "thirdparty/speex/libspeexdsp/jitter.c"]
 
-
 # etc
 
 env.Append(CPPPATH=["thirdparty"])
diff --git a/demo/bin/onevoip.gdextension b/demo/bin/onevoip.gdextension
index 391d7cf..0ed3351 100644
--- a/demo/bin/onevoip.gdextension
+++ b/demo/bin/onevoip.gdextension
@@ -6,4 +6,5 @@ compatibility_minimum = 4.2
 [libraries]
 
 windows.debug.x86_64="res://bin/libonevoip.windows.template_debug.x86_64.dll"
-linux.debug.x86_64="res://bin/libonevoip.linux.template_debug.x86_64.so"
\ No newline at end of file
+linux.debug.x86_64="res://bin/libonevoip.linux.template_debug.x86_64.so"
+macos.debug.arm64="res://bin/libonevoip.macos.template_debug.framework"
diff --git a/demo/project.godot b/demo/project.godot
index dcfe73b..62db50e 100644
--- a/demo/project.godot
+++ b/demo/project.godot
@@ -17,6 +17,7 @@ config/features=PackedStringArray("4.2", "GL Compatibility")
 [audio]
 
 driver/enable_input=true
+driver/mix_rate=48000
 
 [rendering]
```

**Comment by cgodley** [comment]
The left ear issue seems to be a problem in the CoreAudio driver of Godot Engine.

Until that is fixed, it might make sense to just always convert the input signal to mono. That would fix the left ear issue for anyone with a mac with a 1-channel microphone.

### Details
My mac m1 microphone only has 1 channel, but`audio_driver_coreaudio.cpp` is setting `kAudioUnitProperty_StreamFormat` and `capture_channels` to use 2 channels. I suspect`AudioUnitGetProperty` should be grabbing information from `kAudioUnitScope_Input` and not `kAudioUnitScope_Output`. When I make that change (below) and recompile the engine, it correctly detects 1 channel.
```diff
- result = AudioUnitGetProperty(input_unit, kAudioUnitProperty_StreamFormat, kAudioUnitScope_Output kInputBus, &strdesc, &size);
+ result = AudioUnitGetProperty(input_unit, kAudioUnitProperty_StreamFormat, kAudioUnitScope_Input, kInputBus, &strdesc, &size);
	ERR_FAIL_COND_V(result != noErr, FAILED);

	switch (strdesc.mChannelsPerFrame) {
		case 1: // Mono
			capture_channels = 1;
```
